

###

POST http://192.168.10.202:8080/api/agentic/queue?mode=all&actor=Dani
Content-Type: application/json

{
}

###


POST http://localhost:8080/api/agentic/queue?mode=all&actor=Dani
Content-Type: application/json

{
}